export const GET_FIRST_TEAM_NAME = "GET_FIRST_TEAM_NAME";
export const SUCCESS = "SUCCESS";
export const FAILURE = "FAILURE";
export const GET_SECOND_TEAM_NAME = "GET_SECOND_TEAM_NAME";
export const FETCH_TEAMS = "FETCH_TEAMS";
export const FETCH_SUCCESS = "FETCH_SUCCESS";
export const FETCH_FAILURE = "FETCH_FAILURE";
export const POST_DATA = "POST_DATA";
export const RESTART = "RESTART";
export const CHANGE_RESET_CONDITION = "export const CHANGE_RESET_CONDITION=";
